In [3]:
import numpy as np
mt=np.arange(0,20)

In [33]:
mt2=np.reshape(mt,(5,4),order='C')
print(mt2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


question- how do we print the value 10 from above matrix

In [29]:
print(mt2[2,2]) #as the index starts from 0.

10


In [34]:
mt3=np.reshape(mt,(5,4),order='F')
print(mt2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [32]:
print(mt3[0,2])

10
